"""init schema

Revision ID: 6aeda3c114e0
Revises: 
Create Date: 2026-02-22 23:16:41.314159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aeda3c114e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('solicitation_number', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('agency', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('naics', sa.String(length=20), nullable=True),
    sa.Column('fsc', sa.String(length=10), nullable=True),
    sa.Column('set_aside', sa.String(length=80), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_solicitation_number'), 'opportunities', ['solicitation_number'], unique=False)
    op.create_index(op.f('ix_opportunities_source'), 'opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('opportunity_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_analysis_opportunity_id'), 'opportunity_analysis', ['opportunity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_analysis_opportunity_id'), table_name='opportunity_analysis')
    op.drop_table('opportunity_analysis')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_solicitation_number'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
