"""add vendor opportunity matches table (patched safe migration)

Revision ID: 7f7a57fa58ea
Revises: f1a2b3c4d5e6
Create Date: 2026-03-15

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "7f7a57fa58ea"
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names()


def _index_exists(inspector, table_name: str, index_name: str) -> bool:
    try:
        return any(ix.get("name") == index_name for ix in inspector.get_indexes(table_name))
    except Exception:
        return False


def _unique_exists(inspector, table_name: str, constraint_name: str) -> bool:
    try:
        return any(c.get("name") == constraint_name for c in inspector.get_unique_constraints(table_name))
    except Exception:
        return False


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Only create this table when its FK targets already exist.
    # This prevents migration failure on databases where vendor tables were not
    # created yet or the migration chain drifted.
    if _table_exists(inspector, "vendors") and _table_exists(inspector, "opportunities"):
        if not _table_exists(inspector, "vendor_opportunity_matches"):
            op.create_table(
                "vendor_opportunity_matches",
                sa.Column("id", sa.Integer(), primary_key=True),
                sa.Column("vendor_id", sa.Integer(), sa.ForeignKey("vendors.id"), nullable=False),
                sa.Column("opportunity_id", sa.Integer(), sa.ForeignKey("opportunities.id"), nullable=False),
                sa.Column("match_reason", sa.String(), nullable=True),
                sa.Column("confidence_score", sa.Float(), nullable=True),
                sa.Column("source", sa.String(), nullable=True),
                sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
            )

        inspector = sa.inspect(bind)

        if not _index_exists(inspector, "vendor_opportunity_matches", "ix_vendor_opportunity_matches_vendor_id"):
            op.create_index(
                "ix_vendor_opportunity_matches_vendor_id",
                "vendor_opportunity_matches",
                ["vendor_id"],
            )

        if not _index_exists(inspector, "vendor_opportunity_matches", "ix_vendor_opportunity_matches_opportunity_id"):
            op.create_index(
                "ix_vendor_opportunity_matches_opportunity_id",
                "vendor_opportunity_matches",
                ["opportunity_id"],
            )

        if not _unique_exists(inspector, "vendor_opportunity_matches", "uq_vendor_match_vendor_opp"):
            op.create_unique_constraint(
                "uq_vendor_match_vendor_opp",
                "vendor_opportunity_matches",
                ["vendor_id", "opportunity_id"],
            )

    # Intentionally removed unrelated autogenerated schema changes from this
    # migration. They were causing drift and can be handled by their own
    # dedicated migrations if still needed.


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if _table_exists(inspector, "vendor_opportunity_matches"):
        if _index_exists(inspector, "vendor_opportunity_matches", "ix_vendor_opportunity_matches_opportunity_id"):
            op.drop_index("ix_vendor_opportunity_matches_opportunity_id", table_name="vendor_opportunity_matches")
        if _index_exists(inspector, "vendor_opportunity_matches", "ix_vendor_opportunity_matches_vendor_id"):
            op.drop_index("ix_vendor_opportunity_matches_vendor_id", table_name="vendor_opportunity_matches")
        if _unique_exists(inspector, "vendor_opportunity_matches", "uq_vendor_match_vendor_opp"):
            op.drop_constraint("uq_vendor_match_vendor_opp", "vendor_opportunity_matches", type_="unique")
        op.drop_table("vendor_opportunity_matches")
